apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-controller-manager-binding
subjects:
  - kind: ServiceAccount
    name: operator-controller-manager
    namespace: operator-system
roleRef:
  kind: ClusterRole
  name: operator-controller-manager-role
  apiGroup: rbac.authorization.k8s.io
