---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.kirillesikov.atwebpages.com
  resources:
  - kirillapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kirillesikov.atwebpages.com
  resources:
  - kirillapps/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kirillesikov.atwebpages.com
  resources:
  - kirillapps/status
  verbs:
  - get
  - patch
  - update
