apiVersion: apps.kirillesikov.atwebpages.com/v1
kind: KirillApp
metadata:
  name: kirillapp-sample
  namespace: operator-system  
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
    app: kirillapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kirillapp
      containers:
      - name: radio
        image: kyesikov/radio:latest
        ports:
        - containerPort: 3000  
          
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: radio-service
spec:
  selector:
    app: kirillapp
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
