apiVersion: apps.kirillesikov.atwebpages.com/v1
kind: KirillApp
metadata:
  name: kirillapp-sample
  namespace: operator-system  
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
    app: kirillapp
spec:
  replicas: 2
    containers:
      name: kirillapp     
      image: kyesikov/radio:latest  # Example image, replace with your `image` field
      port: 
        containerPort: 3000
  resources:
    limits:
      memory: "512Mi"  # Example resource limits, adjust according to your CRD
      cpu: "1"
    requests:
      memory: "256Mi"                                                
      cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: radio-service
spec:
  selector:
    app: kirillapp
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
