apiVersion: apps.kirillesikov.atwebpages.com/v1
kind: KirillApp
metadata:
  name : kirillapp-sample
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
    app: kirillapp
spec:
  size: 3
  replicas: 2
  name: kirillapp-sample
  image: kyesikov/radio:latest  # Example image, replace with your `image` field
  port: 3000  # Example port, replace with your `port` field
  resources:
    limits:
      memory: "512Mi"  # Example resource limits, adjust according to your CRD
      cpu: "1"
    requests:
      memory: "256Mi"                                                
      cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: radio-service
spec:    
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: kirillapp
  type: LoadBalancer
