apiVersion: apps.kirillesikov.atwebpages.com/v1
kind: KirillApp
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: kirillapp-sample
spec:
  replicas: 2
  image: kyesikov/radio:latest
  containerPort: 3000
      imagePullSecrets:
      - name: radiosecret
---
apiVersion: v1
kind: Service
metadata:
  name: radio-service
spec:
  selector:
    app: radio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
